---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/12 15:56
---

local pb = require("pb")
local user_pb = require('user_pb')

local person= user_pb.Friend()
person.zswnameb = -855.9687
person.address = false
person.ad = 1
person.ad1 = -562949953421312
person.ad2 = 1125899906842624
person.ad3 = 4294967295
person.ad4 = -2147483647
person.ad5 = "sdf只是问问二翁绕弯儿翁"
person.ad6 = -2147483647
person.ad7 = 562949953421312
person.ad8 = 2147483647
person.ad9 = 562949953421312
person.ad10 = string.char(112,113,114,115)


local data = person:SerializeToString()
print("***************************************----SerializeToString-----data----")
pb.ZswLuaShowBytesToString(data)



local msg = user_pb.Friend()
msg:ParseFromString(data)
print("msg**********************************************************************",msg.zswnameb)
print("msg**********************************************************************",msg.address)
print("msg**********************************************************************",msg.ad)
print("msg**********************************************************************",msg.ad1)
print("msg**********************************************************************",msg.ad2)
print("msg**********************************************************************",msg.ad3)
print("msg**********************************************************************",msg.ad4)
print("msg**********************************************************************",msg.ad5)
print("msg**********************************************************************",msg.ad6)
print("msg**********************************************************************",msg.ad7)
print("msg**********************************************************************",msg.ad8)
print("msg**********************************************************************",msg.ad9)
print("msg**********************************************************************",msg.ad10)




